---
output: github_document
---

```{r setup, include = FALSE}

knitr::opts_chunk$set(echo = TRUE)

```

### Special thanks to the National Science Foundation

Collection of the the data provided in this repository was supported by awards from the National Science Foundation to Colorado State University (DEB 0717367, 1147369, 1655035)

### Description of data collection

Experimental and sampling designs as well as descriptions of data collection procedures can be found in: 

1. Bilyeu, D. M., D. J. Cooper, and N. T. Hobbs. 2007. Assessing impacts of large herbivores on shrubs: tests of scaling factors for utilization rates from shoot-level measurements. Journal of Applied Ecology 44:168-175.

2. Bilyeu, D. M., D. J. Cooper, and N. T. Hobbs. 2008. Water tables constrain height recovery of willow on Yellowstone's northern range. Ecological Applications 18:80-92.

3. Marshall, K. N., N. T. Hobbs, and D. J. Cooper. 2013. Stream hydrology limits recovery of riparian ecosystems after wolf reintroduction. Proceedings of the Royal Society B-Biological Sciences 280.

4. Marshall, K. N., D. J. Cooper, and N. T. Hobbs. 2014. Interactions among herbivory, climate, topography and plant age shape riparian willow dynamics in northern Yellowstone National Park, USA. Journal of Ecology 102:667-677.

### Description of files

1. fall_height_data_2001_2020.csv contains annual  measurements of height of individual willows at the end of the growing season. Metadata are found in fall_height_data_metadata.pdf. 	

2. browsing_data_2003_2020.csv contains annual plant level observations of the number of stems browsed out of a sample of observed stems on individual willow plants during spring. Meta data are found in browsing_data_metadata.pdf
		
3. spring_height_data_metadata.pdf contains annual observations of 
 + heights of individual willows at the beginning of the growing season
 + change in  height during the preceding winter
 + change in height during the growing season.  Metadata are found in spring_height_data_metadata.pdf.
    
4. mass_inc_loss_data_2003_2017.csv contains annual observations of  
 + mass of sample of stems on individual willows during the fall and spring.
 + change in stem mass during winter
 + change in stem mass during the growing season
  
5. well_data_2002_2020.csv contains monthly measurements of water table depth during the growing season.  Metadata are found in well_metadata.pdf

### Terms of use

These data may be used for teaching and other educational purposes. The data may be use freely in scientific research and publication after January 1, 2023. The NSF awards supporting the collection of these data shall be aknowledged in any publications using the data.




